#!/usr/bin/env bash

SELECT 15 BETWEEN 1 AND 20;
SELECT 150 BETWEEN 1 AND 20;
SELECT 150 NOT BETWEEN 1 AND 20;

SELECT 10 IN(0,10,20,30);
SELECT 11 IN(0,10,20,30);

SELECT NULL IS NULL;
SELECT '' IS NULL;
SELECT 'NULL' IS NULL;
SELECT 0 IS NULL;

SELECT * FROM `test`;
SELECT * FROM `test` WHERE `first_name` IS NULL;
SELECT * FROM `test` WHERE `first_name` IS NOT NULL;




